apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sigloop
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-card-service.yaml
  - deployment-api-service.yaml
  - deployment-frontend.yaml
  - deployment-landing.yaml
  - service-card-service.yaml
  - service-api-service.yaml
  - service-frontend.yaml
  - service-landing.yaml
  - ingress-web.yaml
  - ingress-api.yaml

